// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Text View",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Text View",
            targets: ["AppModule"],
            bundleIdentifier: "com.gdb.tendril",
            teamIdentifier: "9VV558X8J3",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .boat),
            accentColor: .presetColor(.teal),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/kyle-n/HighlightedTextEditor", "2.1.0"..<"3.0.0"),
        .package(url: "https://github.com/gdbing/SwiftChatGPT", "1.1.0"..<"2.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "HighlightedTextEditor", package: "HighlightedTextEditor"),
                .product(name: "SwiftChatGPT", package: "SwiftChatGPT")
            ],
            path: ".",
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
